// config.ts
export const API_ENDPOINT = 'http://localhost:3000/api';
export const BEARER_TOKEN = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzBhMWE3NDRiZjM2NDU4ZjZmOGMyYmYiLCJlbWFpbCI6InV6YWlybWFobWVkYWRtaW5AZ21haWwuY29tIiwidXNlcnR5cGUiOiJhZG1pbiIsImlhdCI6MTcyODc2MDM1OSwiZXhwIjoxNzI4NzYzOTU5fQ.cmAY9XX3Xxpm0dqo9Hq9LxGdOayHVGI0nzPV8rHgfh0';